services:
  node1:
    build: .
    container_name: node1
    ports:
      - "5001:5000"
    environment:
      - NODE_NAME=node1
      - PEERS=node2:5000,node3:5000
      - MODE=CP
    networks:
      - capnet

  node2:
    build: .
    container_name: node2
    ports:
      - "5002:5000"
    environment:
      - NODE_NAME=node2
      - PEERS=node1:5000,node3:5000
      - MODE=CP
    networks:
      - capnet

  node3:
    build: .
    container_name: node3
    ports:
      - "5003:5000"
    environment:
      - NODE_NAME=node3
      - PEERS=node1:5000,node2:5000
      - MODE=CP
    networks:
      - capnet

networks:
  capnet:
    name: capnet
    driver: bridge